#_BASE_: "../../Base-RCNN-C4.yaml"
_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/home/wsjc/Sxkai/new/EHD-Net/heatmap/NEU/3+3/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    # Maximum number of foreground classes to expect
    NUM_CLASSES: 6
    # Flag to turn on/off Incremental Learning
    LEARN_INCREMENTALLY: False
    # Flag to select whether to learn base classes or iOD expanded classes
    TRAIN_ON_BASE_CLASSES: False
    # Number of base classes; these classes would be trained if TRAIN_ON_BASE_CLASSES is set to True
    NUM_BASE_CLASSES: 3
    # Number of novel classes; these classes would be trained if TRAIN_ON_BASE_CLASSES is set to False
    NUM_NOVEL_CLASSES: 3
    POSITIVE_FRACTION: 0.25
    NMS_THRESH_TEST: 0.3
  RPN:
    FREEZE_WEIGHTS: False
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval',)
  TEST: ('voc_2007_test',)
SOLVER:
  STEPS: (122000,) # 21000, 22000
  MAX_ITER: 14000  # 36000
  WARMUP_ITERS: 1000 # 100
  LR_SCHEDULER_NAME: FixedLR
  EXPLICIT_LR: 0.0001
  CHECKPOINT_PERIOD: 200

OUTPUT_DIR: /home/wsjc/Sxkai/new/EHD-Net/heatmap/NEU/ft_3_3
VIS_PERIOD: 13000

DISTILL:
  ENABLE: False
  BACKBONE: True
  RPN: False
  ROI_HEADS: True
  ONLY_FG_ROIS: False
  # (1-LOSS_WEIGHT) (CLF / REG loss) + (LOSS_WEIGHT) ROI-Distillation
  LOSS_WEIGHT: 0.2
#  LOSS_WEIGHT: 0.3

# Warp Grad
WG:
  ENABLE: False
  TRAIN_WARP_AT_ITR_NO: 20
#  WARP_LAYERS: ("module.roi_heads.res5.2.conv3.weight",)
  WARP_LAYERS: ("module.roi_heads.box_head.fc2.weight",)
  NUM_FEATURES_PER_CLASS: 100
  NUM_IMAGES_PER_CLASS: 10
  BATCH_SIZE: 2
  USE_FEATURE_STORE: True
  IMAGE_STORE_LOC: '/home/wsjc/Sxkai/new/EHD-Net/heatmap/NEU/image_store/image_store_19.pth'

SEED: 9999
VERSION: 2

FINETUNE:
  ENABLE: True
  MIN_NUM_IMG_PER_CLASS: -1
  BATCH_SIZE: 2